// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evmwjqsktchlwxhrqxyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bXdqcXNrdGNobHd4aHJxeHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjQ5OTQsImV4cCI6MjA3NDMwMDk5NH0.utwfXjMW5XbjiJ_1hyw-E3_C7XAH7Hmh4UhUpEHZi3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});